- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: true
      tags:
      - node
      - zsh
      - dotfiles
      - ssh
  tasks:
    - name: .zsh Tasks
      ansible.builtin.include_tasks:
        file: ./tasks/zsh.yml
    - name: Node Tasks
      ansible.builtin.include_tasks:
        file: ./tasks/node.yml
    - name: SSH Tasks
      ansible.builtin.include_tasks:
        file: ./tasks/ssh.yml
